### ISSUE TITLE
Add support for multiple editors

### ISSUE THREAD

**Issue by andreykurenkov** [skynettoday/skynet-today#41]

**Comment by joshuamorton** [comment]
How do you want multi-author to look? Multi-editor is pretty straightforward I think. Authors isn't.

**Comment by andreykurenkov** [comment]
hmm yeah authors is a bit more tricky. I was thinking just stack vertically for both. Liquid has nice support for for loops so it should be pretty easy to modify current html template to just iterate over a list and stack divs  horizontally. Might also make an if - else for single vs multiple, I'd guess that will simplify it a bit.

**Comment by andreykurenkov** [comment]
If authors proves too annoying can also defer and just support multiple editors for now
