### ISSUE TITLE
Google Duplex Editorial

### ISSUE THREAD

**Issue by limorigu** [skynettoday/skynet-today#51]
Google released two audio recording of a conversation between an AI-powered assistant and human service providers. The result was amazing: from deceleration about Turing test passing to meditations about what it means about human nature. This is a classic case of hype in a teacup, but there are a few take-aways: 1) hold your horses, we're not there yet. They didn't even give a live-demo 2) google could have been more clear to begin with, though to be honest what we have heard IS amazing. However, companies should be responsible about not over-hyping either 3) if people contemplate the essence of our humanity after two calls to make reservations... what's in store when AIs do become more human-like? We need to start this discussion, soberly, about now, and brace ourselves for the future (while being quite excited about it too!)

**Comment by andreykurenkov** [comment]
➤ Andrey Kurenkov commented:

@abisee actually going to get around to finishing this up this weekend, let's get out by Wednesday
