### ISSUE TITLE
Deepmind grid cell story

### ISSUE THREAD

**Issue by viraat** [skynettoday/skynet-today#59]

**Comment by AidanRocke** [comment]
@viraat @andreykurenkov You guys might find this thread useful: https://twitter.com/janexwang/status/995229507148828672

Having done some behavioural neuroscience research(on C. Elegans) in the past, I can say that depending on how you want to approach this it can be very technical from a neuroscience perspective.

**Comment by andreykurenkov** [comment]
Outdated
